{
	# xp :
	xp: transaction_aggregate(where: {
    	_and: [
        { type: { _eq: "xp" }}, 
        {event: { object: { name: { _eq: "Module" } } } }
      	]
  	}){
    	aggregate{
      		sum{
        		amount
      		}
    	}
  	}

	# level :
  	level: transaction_aggregate(where: {type: {_eq: "level"}}, order_by: {id : desc}, limit: 1){
    	aggregate{
      		max{amount}
    	}
  	}

	# total audits :
	TotalAudits: user{
    	audits_aggregate(where: {closureType: {_eq: succeeded}}){
    	  aggregate{
    	    count
    	  }
    	}
  	}

	# audit auditRatio :
	AuditRatio: user{
    	auditRatio
  	}


	# skills :
	skills:  user {
    	transactions(
    	  where: {type: {_like: "%skill%"}}
    	  distinct_on: type
    	  order_by: [{type: asc}, {amount: desc}]
    	) {
    	  skillType: type
    	  skillAmount: amount
    	}
  	}

	# projects :
    user{
      infos : 
      	totalUp
      	totalDown
      	auditRatio
		labels{
        	labelName
      	}
      	xps {
        	amount
        	originEventId
        	userId
      	}
     		login
    		lastName
      	firstName
      	attrs
    	Transactions : transactions(where:{
       	 	_and: [
              {transaction_type: {type: {_eq: "xp"}}},
			  {event: {object: {name: {_eq: "Module"}}}}
        	]
    		}order_by :{createdAt: desc}
    	){
      		amount
      		createdAt
      		object{
        		type
        		name
        		progresses{
        	  		group{
        	    		captainLogin
        	    		members{
        	    	  	userLogin
        	    		}
        	  		}
        		}
      		}
    	}
  	}

	#audits
	audits: user{
        succeeded :audits_aggregate(where: {closureType: {_eq: succeeded}}){
        	aggregate{
          	count
        	}
      	}
      failed: audits_aggregate(where: {closureType: {_eq: failed}}){
        	aggregate{
          	count
        	}
      	}
  }
}